---
title: "Volcano Eruptions"
author: "Julia Silge and Sawibrah"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
#knitr::opts_chunk$set(cache = TRUE, warning = FALSE,
#                  message = FALSE, echo = TRUE, dpi = 180, fig.width = 8, fig.height = 5)
library(tidyverse)
#library(silgelib)
#theme_set(theme_plex())
theme_set(theme_light())
```
Let's buid a model for [volcano eruption from this week's #tidytuesday dataset](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-05-12/readme.md). Let's build a multiclass random forest classifer to predict the type of volcano based on other volcano characteristics like latitude, longitude, tectonic setting, etc.

## Explore the date

```{r}
# Get the Data
volcano_raw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')

# eruptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv')
# events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/events.csv')
# tree_rings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/tree_rings.csv')
# sulfur <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/sulfur.csv')

```

```{r}
volcano_raw %>%
  count(primary_volcano_type, sort = T)
# we notice to much categories for small observation 958
# volcano %>% glimpse()
```
```{r}
volcano_df <- volcano_raw %>% 
  transmute(volcano_type = case_when(str_detect(primary_volcano_type, "Stratovolcano") ~ "Stratovolcano", 
                                     str_detect(primary_volcano_type, "Shield") ~ "Shield",
                                     TRUE ~"Other"),
            volcano_number, latitude, longitude, elevation, tectonic_settings, major_rock_1) %>%
  mutate_if(is.character, factor)
```

```{r}
world <- map_data("world")

ggplot()+
  geom_map(data = world, map=world, aes(long, lat, map_id = region))
```


```{r}
world <- map_data("world")

ggplot() +
  geom_map(data = world, map = world, 
           aes(long, lat, map_id = region),
           color = 'white', fill='gray50', alpha=0.2)+
  geom_point(data = volcano_df, 
             aes(longitude, latitude, color=volcano_type),
             alpha = 0.8)
```


## Build a model
```{r}
library(tidymodels)
# due to the small size of the data we are going to a create a boostrap
volcano_boot <- bootstraps(volcano_df) # create 25 bootstrap samples
volcano_boot
```


```{r}
library(themis)

volcano_rec <- recipe(volcano_type ~ ., data = volcano_df) %>%
  update_role(volcano_number, new_role = "Id") %>%
  step_other(tectonic_settings) %>%
  step_other(major_rock_1) %>%
  step_dummy(tectonic_settings, major_rock_1) %>%
  step_zv(all_predictors()) %>%
  step_normalize(all_predictors()) %>%
  step_smote(volcano_type)

volcano_prep <- prep(volcano_rec)
#volcano_prep
#juice(volcano_prep)
#juice(volcano_prep) %>% count(volcano_type)
```

```{r}
rf_spec <- rand_forest(trees = 1000) %>%
  set_mode("classification") %>%
  set_engine("ranger")

volcano_wf <- workflow() %>%
  add_recipe(volcano_rec) %>%
  add_model(rf_spec)

volcano_wf
```


```{r}
volcano_res <- fit_resamples(
  volcano_wf,
  resamples = volcano_boot,
  control = control_resamples(save_pred = T,
                              verbose = T)
)
```


## Explore results
```{r}
volcano_res %>%
  collect_metrics()
```

```{r}
volcano_res %>%
  collect_predictions() %>%
  conf_mat(volcano_type, .pred_class)
```


```{r}
volcano_res %>%
  collect_predictions() %>%
  ppv(volcano_type, .pred_class) # positive predicted values
```

```{r}
volcano_res %>%
  collect_predictions() %>%
  group_by(id) %>%
  ppv(volcano_type, .pred_class) # positive predicted values
```

```{r}
volcano_res %>%
  collect_predictions() %>%
  group_by(id) %>%
  ppv(volcano_type, .pred_class)  %>% # positive predicted values
  ggplot(aes(.estimate)) + geom_histogram(bins=10)
```


```{r}
library(vip) # variable importance

rf_spec %>%
  set_engine("ranger", importance = "permutation") %>%
  fit(
    volcano_type ~ .,
    data = juice(volcano_prep)%>% 
      select(-volcano_number) %>% 
      janitor::clean_names()
  ) %>%
  vip(geom = "point")
```

```{r}
volcano_pred <- volcano_res %>%
  collect_predictions() %>%
  mutate(correct = volcano_type == .pred_class)  %>%
  left_join(volcano_df %>% 
              mutate(.row = row_number()))

volcano_pred
```

```{r}
ggplot() +
  geom_map(data = world, map = world, 
           aes(long, lat, map_id = region),
           color = 'white', fill='gray50', alpha=0.2)+
  stat_summary2d(data = volcano_pred, aes(longitude, latitude, z = as.integer(correct)),
                                          fun = 'mean',
                                          alpha = 0.7)
```


```{r}
ggplot() +
  geom_map(data = world, map = world, 
           aes(long, lat, map_id = region),
           color = 'white', fill='gray50', alpha=0.2)+
  stat_summary_hex(data = volcano_pred, aes(longitude, latitude, z = as.integer(correct)),
                                          fun = 'mean',
                                          alpha = 0.7) 
```



```{r}
ggplot() +
  geom_map(data = world, map = world, 
           aes(long, lat, map_id = region),
           color = 'white', fill='gray50', alpha=0.2)+
  stat_summary_hex(data = volcano_pred, aes(longitude, latitude, z = as.integer(correct)),
                                          fun = 'mean',
                                          alpha = 0.7, bin =  60) +
  scale_fill_gradient(high = 'cyan3', labels = scales::percent) +
  labs(fill = "Percent classified\ncorrectly")
  
```